### ISSUE TITLE
Revisar que estén todas las propiedades de MCD

### ISSUE THREAD

**Issue by fjsaezm** [libreim/apuntesDGIIM#22]
Revisar en el archivo /Algebra/tema1.tex

**Comment by SofiaAlmeida** [comment]
No están todas
La primera que hay pasada es la que yo tengo como propiedad 9
Lo que falta es justo la definición de MCD, las primeras propiedades y ya lo de después de DIP

**Comment by fjsaezm** [comment]
Perdón, puse el Issue sin hacer el push. Está añadido algunas cosas pero no todas. Las que faltan mañana se las pido antonio y luego las paso.
