### ISSUE TITLE
Sobre la asignatura de Estructura de Computadores

### ISSUE THREAD

**Issue by fjsaezm** [libreim/apuntesDGIIM#25]
Creo que podría estar bien hacer un documento (escrito como queráis), que sea como una especie de *recetario* de las instrucciones en esamblador, con lo que hacen , los parámetros que necesitan y tal y quizá algunos ejemplos. Comentad cómo lo veis y si os parece bien lo intentamos, no creo que tardemos mucho.

**Comment by jojelupipa** [comment]
Yo estoy empezando un archivo con algunas instrucciones de ensamblador, ya lo vamos completando según veamos :-) :+1:
