### ISSUE TITLE
Sobre el calendario.

### ISSUE THREAD

**Issue by danipozo** [libreim/apuntesDGIIM#26]
Deberíamos mantenerlo actualizado o bien eliminarlo.

**Comment by mroman42** [comment]
Hay un proyecto de calendarios en @libreim/calendar. El problema es que sólo está siendo actualizado el de tercero y además lo tenemos mal colocado. Se podría intentar recuperar ese proyecto http://tux.ugr.es/dgiim/calendar/

**Comment by danipozo** [comment]
Sí, quizá sería lo mejor recuperar ese proyecto. ¿Qué hay que hacer para agregar fechas de exámenes a ese calendario?

**Comment by mroman42** [comment]
En el repositorio de los calendarios teníamos todo organizado: https://github.com/libreim/calendar . Incluso con una issue en la que intentábamos elegir responsables por curso. Todo esto se hizo el año pasado pero no hemos vuelto a actualizar nada. Creo que los permisos sobre los calendarios los tiene la antigua cuenta de correo de dgiim, así que tendré que ponerme a actualizar todo.

En cualquier caso, si no os parece mal, podemos tratar esto por el repo del calendario.
