### ISSUE TITLE
Completar apuntes.tex

### ISSUE THREAD

**Issue by antcc** [libreim/apuntesDGIIM#3]
- Completar el archivo de apuntes con demostraciones, notas aclaratorias, ejemplos, etc.
- Sería bueno ir escribiendo lo que se hace en cada momento, qué se persigue con el estudio de determinados conceptos, y hacia donde está encaminado. No debe tratarse, a diferencia del archivo **resultados.tex**, de una catarata de teoremas, proposiciones y corolarios.
- Revisar el archivo para detectar fallos y/o erratas.

**Comment by danipozo** [comment]
Esto se está llevando a cabo de forma continua, según vamos dando clase. Para solicitar que se añadan resultados, demostraciones u otro tipo de contenido adicional de forma puntual, o que se revisen partes del contenido, bien porque se acaben de añadir o bien porque se sospeche la presencia de un error, es mejor abrir _issues_ específicas. Por tanto, cierro esta.
