### ISSUE TITLE
Problemas de espaciado

### ISSUE THREAD

**Issue by fjsaezm** [libreim/apuntesDGIIM#32]
A veces, me da la sensación en los apuntes en general (todos tienen la misma plantilla) de que está todo un poco pegado, apelotonado.
¿Qué opináis?
¿Se podría hacer algo para que, si estais de acuerdo, se ampliaran un poco los interlineados o espacios entre "environments" y que quedara algo mejor presentado?

**Comment by antcc** [comment]
Yo tengo la misma sensación, me parecería bien que se aumentara ligeramente el interlineado.

**Comment by fjsaezm** [comment]
He aumentado el interlinado de los apuntes de álgebra y de los de análisis. Decidme qué opinais.
