### ISSUE TITLE
Licencia en la plantilla de apuntes.

### ISSUE THREAD

**Issue by danipozo** [libreim/apuntesDGIIM#34]
Quizá deberíamos añadir la licencia (Creative Commons) en la plantilla de los apuntes, para que quede en los PDF resultantes o en el material impreso, junto con alguna referencia a este repositorio.

Además, he visto la licencia exacta que tenemos puesta y es la Attribution 4.0 International, que permite usar el material con cualquier propósito, incluso comercial, bajo la sola condición de que se atribuya el trabajo a su autor original. Creo que deberíamos cambiarla por una licencia *copyleft* (Share Alike en el caso de Creative Commons).

**Comment by antcc** [comment]
Ya se ha realizado el cambio de licencia, y se ha añadido un distintivo en los apuntes en PDF de las asignaturas de matemáticas. Falta discutir si deberíamos hacer lo propio con las asignaturas de informática, y con los archivos de ejercicios resueltos de matemáticas, que no son exactamente apuntes.

**Comment by fjsaezm** [comment]
Los ejercicios no creo que deban tener esa licencia. Las asignaturas de informática creo que también deberían llevar la *licencia*

**Comment by jmml97** [comment]
Todos los archivos de apuntes deberían tener licencia, ¿no? También los ejercicios deberían tener licencia.

**Comment by danipozo** [comment]
Estoy de acuerdo con @jmml97.
