### ISSUE TITLE
Entorno: propiedades

### ISSUE THREAD

**Issue by fjsaezm** [libreim/apuntesDGIIM#36]
Quizá estaría bien crear un environment, o como se llame, para las propiedades de las cosas

**Comment by antcc** [comment]
¿A qué te refieres exactamente con las propiedades? Si te refieres a una lista de propiedades, ya existe el entorno *nlist* en la plantilla de matemáticas.

**Comment by fjsaezm** [comment]
No sé, mi idea era facilitar el que al tener el entorno apareciera directamente un **Propiedades:** y estuvieras "dentro" de un *nlist* para que se pudeira hacer algo del estilo:
\begin{props}
\item $a = b sii b = a$
\end{props}

y el resultado fuera algo así como:
**Propiedades:**
+ a=b sii b=a

**Comment by jmml97** [comment]
¿No consideramos las "Propiedades" como proposiciones o corolarios?

**Comment by antcc** [comment]
Esa era mi impresión también. En cualquier caso se puede debatir, y si lo veis necesario, se puede añadir un entorno de propiedades sin muchos problemas.

**Comment by jmml97** [comment]
Dado que no ha habido mucho debate sobre este tema quizás sea lo suyo cerrar el _issue_ y considerar las propiedades como proposiciones o corolarios.
