### ISSUE TITLE
No funciona el Rakefile

### ISSUE THREAD

**Issue by fjsaezm** [libreim/apuntesDGIIM#40]
El rakefile no produce los PDF de las asignaturas del 2º Cuatrimestre. Probablemente sea porque las he añadido yo o algo y no lo haya hecho bien. Estaría bien que se le diera urgencia a este issue.

**Comment by antcc** [comment]
Arreglado. En el futuro, debemos tener cuidado a la hora de añadir gráficos, o en general, referenciar un archivo mediante ruta relativa. He añadido la siguiente línea en el preámbulo:

*\graphicspath{{../Recursos/Plantillas/}, {Recursos/Plantillas/}}*

Es ahí donde se deben añadir las rutas relativas donde se deben buscar los gráficos, siguiendo el patrón. Después en el cuerpo del documento, debemos referenciar la imagen únicamente por su nombre, omitiendo la ruta.
