### ISSUE TITLE
Compilación Automática

### ISSUE THREAD

**Issue by jojelupipa** [libreim/apuntesDGIIM#47]
Buscar alguna manera, bien por algún servidor o de algún otro modo para que la tarea de generación de los PDF se realice de manera automática.

**Comment by ncordon** [comment]
No había visto esto, pero he metido el progreso o la involución en el issue #45 . Cierro esa issue y pongo los mensajes por aquí?

**Comment by ncordon** [comment]
@jojelupipa @danipozodg @SofiaAlmeida @fjsaezm Tengo una configuración para shippable que compila bien los pdfs, el problema es que tarda demasiado porque tiene `texlive` entero. cacheado Tarda unos 20 minutos, que me parece una burrada, pero no encuentro más alternativas, porque instalar la instalación básica de `texlive` no parece una opción porque le faltan muchos paquetes y cada vez que usarais algo de otro paquete habría que meterlo en el fichero de configuración.

**Comment by danipozo** [comment]
Si compila bien los PDF está bien, aunque tarde 20 minutos. Aunque observo que no está funcionando en cada *commit*, ¿es ese el comportamiento esperado?

**Comment by ncordon** [comment]
@danipozodg Lo tenía desactivado hasta que me dieseis el ok. Lo activo esta noche.

**Comment by danipozo** [comment]
Perfecto, gracias por ayudarnos con esto 💯 . Cierro este *issue*.

**Comment by ncordon** [comment]
Ahora mismo está haciendo push del contenido de `.out` compilado a la rama `pdf`. Si os viene mejor puede cambiarse a que copie la rama `master` con el contenido de `.out` como los pdfs compilados.

**Comment by danipozo** [comment]
En la rama `pdf` está perfecto, así nos evita tener que hacer mezclas cuando hagamos *commits* a la master.
