### ISSUE TITLE
Enlaces a archivos dentro de otros

### ISSUE THREAD

**Issue by antcc** [libreim/apuntesDGIIM#49]
Habría que estudiar la posibilidad de incluir enlaces a archivos dentro de otros archivos. Por ejemplo, enlazar el archivo de Ejercicios dentro del PDF de Apuntes de Análisis II.

También sería ideal poder referenciar una página concreta de otro archivo, o incluso una posición específica, mediante alguna etiqueta o similares. La idea es investigar si esta funcionalidad está disponible, principalmente, para archivos en *Latex*.

**Comment by antcc** [comment]
Para referenciar una línea específica **dentro de un mismo archivo**, puede utilizarse el siguiente código:

> % Crear una etiqueta para ser referenciada más tarde
\phantomsection
\label{nombre_etiqueta}

Así, en cualquier parte del documento se puede referenciar la etiqueta como venimos haciendo normalmente (i.e, *\ref{nombre_etiqueta}*)

**Comment by jmml97** [comment]
@antcc Pero el problema es referenciar otro archivo, ¿no?

**Comment by antcc** [comment]
@jmml97 Cierto, había leído mal mi propia pregunta. Actualizo el comentario, pero sí, aún tenemos ese problema.

**Comment by jmml97** [comment]
Una posible solución a esto podría pasar por incluir los ejercicios dentro del archivo de apuntes. Utilizando `\input{}` o `\include{}` podríamos tener un archivo que contuviese únicamente el texto de los ejercicios y luego el archivo de los apuntes y otro de los ejercicios (que incluiría el preámbulo y luego el `\include{}`). Así podemos hacer referencia a los ejercicios desde los apuntes y mantener un archivo de ejercicios por separado (aunque quizás podría eliminarse, ¿para qué queremos dos archivos de ejercicios?).

**Comment by danipozo** [comment]
Creo que el problema es referenciar una sección de un archivo externo sin necesidad de incluir el contenido. ¿Esa solución lo permite?

**Comment by jmml97** [comment]
No. El problema es que referenciar archivos externos es un poco chungo. Para ello se tiene que conocer la ruta relativa del otro archivo. Si mueves alguno de ellos a otro sitio pierdes la referencia. También es posible que haya visores que no permitan cargar PDF de esta forma, especialmente en móviles. Y si lees el PDF desde el navegador con el enlace creo que tampoco funcionaría.

**Comment by jmml97** [comment]
Bajo la nueva plantilla para los apuntes de Matemáticas (y la futura de `pandoc` para Informática) los apuntes y los ejercicios están bajo un mismo archivo, así que ya no es necesario enlazar a archivos externos, algo complicado técnicamente. Cierro el _issue_.
