### ISSUE TITLE
Mejorar gh-pages

### ISSUE THREAD

**Issue by jojelupipa** [libreim/apuntesDGIIM#50]
Hay asignaturas que enlazan a su carpeta de .out y otras que no (deberíamos "estandarizar" eso). También hay un mensaje "casi completos" en algunas asignaturas, mientras que en otros apuntes que están en peor estado (en comparación) no tienen ningún tipo de indicación.

**Comment by jmml97** [comment]
Dado que ya no hay carpeta .out la primera parte ya está resuelta. Quedaría por revisar lo segundo, por ejemplo en Análisis Matemático I pone "(casi completos)" y sin embargo dentro hay un apartado que dice "FALTAN MUCHAS COSAS".

**Comment by antcc** [comment]
Creo que sería buena idea mantener un archivo similar al *todo.txt* que tenemos para tareas por completar, pero que sean tareas a largo plazo. Un ejemplo claro sería completar los apuntes de las asignaturas del primer cuatrimestre.

**Comment by jmml97** [comment]
Ahora que no tenemos disponible el servidor `tux.ugr.es`, ¿cómo lo hacemos para enlazar a los `.pdf` desde la web?

**Comment by jmml97** [comment]
Página web nueva con nuestro servidor compilando los apuntes.
