### ISSUE TITLE
Estandarizar nombres

### ISSUE THREAD

**Issue by antcc** [libreim/apuntesDGIIM#51]
Creo que sería buena idea estandarizar el nombre de las carpetas y subcarpetas de cada asignatura. Por ejemplo, recursos, resúmenes, imágenes, etc. También el nombre de los archivos (*ej: apuntes.tex para los apuntes*).

**Comment by jmml97** [comment]
Comencé a redactar un pequeño texto sobre la estructura de los apuntes que contiene información sobre esto. Tengo pendiente acabarlo y publicarlo en la wiki o en algún otro lugar que veáis. Me asigno la tarea.

**Comment by jmml97** [comment]
El texto ya está en la wiki. Falta actualizar las asignaturas que ya hay.
