### ISSUE TITLE
Error en: git add <Asignatura_con_tilde>

### ISSUE THREAD

**Issue by jojelupipa** [libreim/apuntesDGIIM#52]
En la nueva rama public, al juntar mi torpeza con mis despistes y las tildes, no sé el motivo por el cual no se puede hacer git add de una asignatura con tildes en el nombre (ni siquiera usando la fuerza bruta " add * ") para indicar en el commit los archivos que han sido borrados.

**Comment by ncordon** [comment]
@jojelupipa A mí me funciona bien en la rama public

**Comment by jojelupipa** [comment]
Al final con *git commit -am* todo funcionaba, cierro ya el issue.
