### ISSUE TITLE
Adaptar asignaturas existentes a la nueva estructura y la nueva plantilla

### ISSUE THREAD

**Issue by jmml97** [libreim/apuntesDGIIM#55]
Hay asignaturas que aún no están adaptadas a la nueva estructura de archivos explicada en la wiki y que tampoco utilizan las nuevas plantillas.

**Comment by delightfulagony** [comment]
Las asignaturas pendientes de adaptar a la nueva estructura son:
- [x] AC
- [x] ALGII
- [x] ALGIII
- [x] AMI
- [x] AMII
- [x] EC
- [x] ED
- [x] FIS
- [x] GEOIII
- [x] ISE
- [x] MMI
- [x] PDOO
- [x] SO
- [x] TOPI
- [x] VCI
Propongo crear issues individuales para cada una de las asignaturas y agruparlas en un proyecto.

**Comment by danipozo** [comment]
Creo que todas o casi todas están adaptadas, particularmente las de matemáticas.

**Comment by jmml97** [comment]
Las únicas asignaturas que no respetan ahora mismo esta estructura son VCI y FIS. He modificado la Wiki para cambiar el nombre de la carpeta 'recursos' a 'img', tal y como están todas ahora mismo.

Algunas asignaturas cuentan con más archivos, además de los definidos en la wiki, que quizás deberían reorganizarse. Pero la estructura de los apuntes como tal sí se respeta.

**Comment by delightfulagony** [comment]
Creo que el nombre img es un poco confuso, quiza seria mejor cambiar el nombre de las carpetas img a recursos y meter todo lo que no sean los archivos `.tex`/`.md`/`.sty` en `recursos`. El unico problema seria cambiar los enlaces en el interior de los documentos.

Me ofrezco para cambiar el nombre de las carpeta `img` a `recursos` si os parece bien.

**Comment by danipozo** [comment]
¿En qué estado se encuentra esto actualmente? ¿Se puede cerrar el *issue*?

**Comment by delightfulagony** [comment]
Acabo de hacer un PR #73 que debería cerrar esta issue.
