### ISSUE TITLE
Mencionar a los autores originales de los trabajos.

### ISSUE THREAD

**Issue by rjraya** [libreim/apuntesDGIIM#63]
Me ha asombrado ver lo bonito que han quedado los apuntes que deje de Algebra I. Pero para cumplir con la licencia habria que mencionar al autor original (en este caso Rodrigo Raya). 

Ocurre algo similar con otros archivos. Por ejemplo, en Probabilidad I, donde no se menciona a los autores  originales. Imagino que esto ocurre en mas casos, asi que es un buen momento para referenciarlos.

**Comment by danipozo** [comment]
Los apuntes que basamos en los tuyos son los de Álgebra II, que tienen una nota de agradecimiento donde se menciona al autor y el repositorio original. En cuanto a los apuntes de Probabilidad, los autores originales los liberaron bajo una licencia MPL 2.0, que, a nuestro entender, no requiere atribución. Es por esto que la atribución quedó relegada al código fuente. Sin embargo, hemos decidido trasladarla al PDF final.

Estos son los dos únicos casos en los que hemos partido de apuntes preexistentes.

**Comment by rjraya** [comment]
Respecto a Álgebra I,  ¿estamos hablando de este fichero?

https://dgiimcloud.ml/PDF/ALGI/algi.pdf

En particular, estamos diciendo que des independiente de este otro:

https://github.com/rjraya/Ring-Theory/blob/master/algebra1.pdf

¿Es eso?

**Comment by danipozo** [comment]
Correcto. Los apuntes del primer enlace fueron tomados durante el curso 2016/17 en clase principalmente y editados sucesivamente por varios colaboradores de este repositorio. La similaridad evidente que existe entre ambos se debe únicamente a que fueron tomados en cursos también muy similares.

**Comment by rjraya** [comment]
¡Estupendo! Creo que hay cosas que faltan en mi documento, ya sé de dónde puedo tomarlas entonces! Creo que ya se puede cerrar el issue.

**Comment by jojelupipa** [comment]
No te olvides de mencionar a los autores  ;)
