### ISSUE TITLE
Migración de Rake a Make

### ISSUE THREAD

**Issue by danipozo** [libreim/apuntesDGIIM#70]
Ahora mismo, el [*script* que compila los apuntes](https://github.com/libreim/apuntesDGIIM/blob/master/Rakefile) está escrito en un sistema específico de Ruby, que no está instalado por defecto en la mayoría de los sistemas.

Migrar a Make tendría la ventaja de eliminar una dependencia que a veces puede ser difícil de instalar (por no estar en los repos de una distribución, por ejemplo) o que obliga a instalar dependencias adicionales de Ruby que solo se usan con ese propósito.

Me gustaría estudiar la viabilidad de esto, y qué desventajas puede tener.

**Comment by fdavidcl** [comment]
Al principio intentamos usar Make pero no hubo manera porque los nombres de directorios y de archivos tenían espacios (y [Make no funciona con espacios en los nombres de archivo](https://stackoverflow.com/a/9838604)). Supongo que ahora que los nombres son más cortos se podría volver a intentar, creo que las ventajas de usar herramientas fáciles de instalar compensarían la restricción de no poder poner espacios en los nombres.

**Comment by mx-psi** [comment]
Me lo asigno para mirarlo en el futuro próximo. Para los espacios podríamos comprobarlo con un webhook (o con un hook local) y evitar así que se suban archivos con espacios en el nombre (o al menos que se nos notifique de alguna forma)

**Comment by mx-psi** [comment]
Estoy empezando a hacer la traducción y no entiendo una cosa de la función `pandoc_rule`. La línea en concreto es [la 37](https://github.com/libreim/apuntesDGIIM/blob/cacdb8943fc57ed926f7505dd35fcc21b7f0d6ec/rake_helpers.rb#L37) y `git blame` dice que la última edición es de @danipozo.

En el Rakefile entiendo que `pandoc_rule` se utiliza para generar las reglas para archivos `.md` y `.org`, sin embargo la orden de `pandoc` sólo hace referencia a ficheros `.md`, y en concreto siempre a `ejercicios.md` y `apuntes.md`. Esto entiendo que implica que

1. no funciona para `.org` por tanto (eso es fácil de arreglar) y
2. siempre son necesarios `apuntes.md` y `ejercicios.md` y se genera un único archivo que combina ambos.

Esta segunda parte contradice las instrucciones del Rakefile:
> Generate a PDF file for **each** corresponding source (LaTeX, Markdown...) file

y me queda entonces la duda de si debería generar un fichero por cada uno por separado (ejercicios y apuntes) o continuar con el comportamiento actual. 

¿Qué debería hacer el nuevo Makefile en relación a esta regla?

**Comment by mx-psi** [comment]
Resuelto vía #77
