### ISSUE TITLE
Arreglar la cabecera de página

### ISSUE THREAD

**Issue by danipozo** [libreim/apuntesDGIIM#71]
La plantilla actual incluye una cabecera de página con los títulos de la sección y la subsección en la que se encuentran, y en muchos casos estos textos se solapan. Además, si alguno de los títulos incluye texto en modo matemático, esto no se tiene en cuenta. Un ejemplo:

![image](https://user-images.githubusercontent.com/15173583/65717198-0b923b00-e0a1-11e9-8b95-3c32fa12a5c0.png)

**Comment by jmml97** [comment]
Lo más fácil es quitar la subsección, que igual no es necesaria.

**Comment by danipozo** [comment]
No tengo problema con esta solución.

**Comment by Alejandro-Villa** [comment]
He encontrado una posible solución, viendo el capítulo 29 punto 3 de la documentación de `fancyhdr`. Se puede poner el título de la sección truncado usando el paquete `truncate`. La documentación está [aquí](https://osl.ugr.es/CTAN/macros/latex/contrib/fancyhdr/fancyhdr.pdf). Me voy a poner a ello y os hago PR. (Edit: se puede trucar el título para que solo se vea parte y no colisione, estoy mirando formas de hacerlo multilínea pero esto sería una primera aproximación)

**Comment by jmml97** [comment]
@Alejandro-Villa ¿la solución que propones en #75 trunca o hace multilínea la cabecera?

Insisto en que creo que sería mejor eliminar la subsección de la cabecera, pues
- truncar la sección y subsección haría la cabecera un poco más inútil —para poner una cabecera incompleta no pongas nada—; 
- extenderla en varias líneas reduce el espacio útil de página, en mi opinión no es estético y es inconsistente.

**Comment by Alejandro-Villa** [comment]
La solución que al final he implementado hace multilínea la cabecera. Que es cierto que ocupa bastante espacio y quita margen inferior. Se podría modificar el tamaño de letra para que se ajuste mejor. Sino pues siempre se puede eliminar

**Comment by danipozo** [comment]
Estoy de acuerdo con @jmml97, aunque creo que aún se pueden considerar:

- Reducir el tamaño de letra de la cabecera, que es más grande que el del cuerpo,
- alternar entre título de sección y de subsección entre las páginas, y
- eliminar el título de sección en lugar del de subsección, ¿cuál es más útil?

**Comment by jmml97** [comment]
Finalmente he eliminado la subsección de la cabecera y he dejado la sección con su número.
