### ISSUE TITLE
Wiki incompleta

### ISSUE THREAD

**Issue by Mapachana** [libreim/apuntesDGIIM#85]
Falta añadir la infromación nueva sobre como compilar apuntes al actualizar los repos, incluyendo versión mínima de cada programa a usar y troubleshooting

**Comment by mx-psi** [comment]
He actualizado [la página de la wiki](https://github.com/libreim/apuntesDGIIM/wiki/C%C3%B3mo-compilar-los-apuntes) con instrucciones para el Makefile.
He empezado también una tabla de compatibilidad; si funciona en otras versiones podemos añadirlo.

¿Qué cosas crees que debería haber en el troubleshooting?

**Comment by mx-psi** [comment]
ping @Mapachana
