### ISSUE TITLE
Tipos de compilado

### ISSUE THREAD

**Issue by Mapachana** [libreim/apuntesDGIIM#86]
Añadir al makefile la opción de compilar con la plantilla antigua o la nueva, según prefiera el usuario

**Comment by jmml97** [comment]
La nueva plantilla tiene mejoras respecto a la anterior y está planteada como sucesora de la misma, no como una opción alternativa. Su desarrollo ya se discutió en #68.

**Comment by mx-psi** [comment]
He añadido los nombres de las plantillas como variables al Makefile para que se pueda usar una plantilla personalizada. 

Creo que no tiene sentido mantener soporte para más de una plantilla (pueden discutirse cambios de la actual) pero esto no suponía ningún cambio importante del Makefile así que lo he añadido
